version: "3"
services:
  db:
    image:  postgres
    container_name: nestjs-fundamentals-db
    restart: always
    ports:
      - "5432:5432"
    environment:
       POSTGRES_PASSWORD: pass123
  test-db:
    image:  postgres
    container_name: nestjs-fundamentals-test-db
    restart: always
    ports:
      - "5433:5432"
    environment:
       POSTGRES_PASSWORD: pass123
  mongo:
    image:  mongo
    container_name: nestjs-fundamentals-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
       MONGODB_DATABASE: nest-course